name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@v0.1.2        
      with:
        path: src

    - uses: actions/upload-artifact@v3
      with:
        name: leihtool.exe
        path: src/dist

